// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"user-center/biz/dal"
)

func init() {
	dal.InitDB()
}

func main() {
	h := server.Default()

	register(h)
	h.Spin()
}
